print("Edwin Laurensius Alexandro Siregar")
print("I0322040")
print("Pematangsiantar")
print("Di lingkungan sekitar saya terdapat banyak tempat kos untuk anak SMA sehingga jarang terlihat anak-anak yang bermain di komplek rumah. Ada juga lapangan tempat untuk olahraga pagi maupun sore, seperti jogging, pull up, bersepeda, dan lain")
print("Harapan saya setelah lulus Teknik Industri UNS adalah mendapat pengetahuan yang luas untuk modal masa depan")